export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};
import '@/src/global.css';

import NavBar from '@/components/nav';

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body>
                <NavBar />
                {children}
            </body>
        </html>
    );
}
